### ISSUE TITLE
License for MPlot?

### ISSUE THREAD

**Issue by zwpwjwtz** [acquaman/MPlot#15]
Hi all, I'm working on a [project](https://github.com/zwpwjwtz/HMDB-qt) that helps visualizing the information retrieved from Human Metabolome Database ([HMDB](https://hmdb.ca)), and MPlot fits exactly the need of displaying mass spectra to users. 
I wonder if I can integrate the source code of MPlot into my project: I use the GPLv3 license for my project, but I didn't find the license information for MPlot. Would you mind adding a license to MPlot, so that I'm sure if it is compatible with GPL?
FYI, I've attached a screenshot of my project, which shows a preliminary design.
![Screenshot_HMDB-qt_20220118114011](https://user-images.githubusercontent.com/8875892/149869811-d5381281-3e4d-454a-a555-880b16cdbeef.png)

**Comment by dretrex** [comment]
Hi there!  Thanks for reaching out.  I have added a GPLv3 license file to the repository.  Good luck with your project!
